version: '3.8'

services:   
  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Basket.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=***:5002
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - Redis__Host=***:6380
      - Redis__CacheTimeout=00:00:10
      - PathBase=http://***:5003
    depends_on:
      - redis
      - rabbitmq
    ports:
      - 5003:5003 
  order.api:
    container_name: lde.order.api
    build:
      context: .
      dockerfile: Order/Order.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005
      - ConnectionString=server=***;port=5433;database=Ordering;uid=postgres;password=postgres;
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - PathBase=http://***:5005
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - 5005:5005
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - ConnectionString=server=***;port=5433;database=GameStore;uid=postgres;password=postgres;
       - Authorization__Authority=http://***:5002
       - PathBase=http://***:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000
  web.mvc:
    container_name: lde.web.mvc
    build:
      context: .
      dockerfile: Web/MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CatalogUrl=http://***:5000/api/v1/catalogbff
      - OrderUrl=http://***:5005/api/v1/order
      - BasketUrl=http://***:5003/api/v1/basketbff
      - Authorization__Authority=http://***:5002
      - IdentityUrl=http://***:5002
      - CallBackUrl=http://***/
      - RedirectUri=http:/***/signin-oidc
    depends_on:
      - catalog.api
      - identityserver
    ports:
      - 5001:5001
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://***
      - CatalogApi=http://***:5000
      - BasketApi=http://***:5003
    ports:
      - 5002:5002
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80 
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  redis:
    image: redis
    container_name: lde.redis
    ports:
      - 6380:6379
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lde.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672 
      - 15672:15672  
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4